# Generated by Django 4.1.5 on 2023-02-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_rename_type_gametype_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(default='Old Mother Hubbard', max_length=150),
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
