# Generated by Django 4.1.5 on 2023-02-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_game_maker_game_number_of_players_game_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='attendee',
            field=models.ManyToManyField(related_name='attendee', to='levelupapi.event'),
        ),
    ]
